= バイナリビルド
:navtitle: バイナリビルド

include::vars.adoc[]

[#moving_on_from_s2i]
== S2I からのステップアップ
前述の通り、S2I はソースコードからコンテナへ移行する優れた方法ですが、日々の迅速な反復開発（iterative development）には少々遅すぎます。
例えば、CSS を変更したり、クラス内のメソッドを 1 つ変更したりする場合、Git コミットとビルドのサイクル全体を実行したくはありません。
このラボでは、迅速な反復開発（iterative development）のためのより効率的な方法を紹介します。
ついでに、コードのデバッグ方法も紹介します。

MLB Parksサービスをビルドしたので、早速変更を加えてみましょう。

[#fast_iterative_code_change_using_binary_deploy]
== バイナリデプロイを使用した高速反復コード変更

OpenShift コマンドラインには、ローカルマシンからデプロイを行う機能があります。今回は S2I を使用しますが、OpenShift にローカルマシンから WARファイルを取得してイメージに組み込むように指示します。

この開発パターンを採用することで、ローカルマシンで迅速にビルドを実行し（ローカルキャッシュとマシンのパワーを最大限に活用）、その後 WARファイルを素早く送信できます。

NOTE: このパターンを使用して、作業ディレクトリを S2I ビルダーに送信し、OpenShift 上で Maven ビルドを実行することもできます。
ローカルディレクトリを使用することで、ローカルマシンに Maven や Java ツールチェーンをインストールする必要がなくなります。


// machine AND would also not require git commit with a push. Read more in the
// {openshift-docs-url}/builds/basic-build-operations.html#builds-basic-start-source_basic-build-operations[official documentation]


[#using_binary_deployment]
== 演習: バイナリデプロイメントの使用

[#clone_source]
=== Clone source
最初のステップは、GitHub からワークショップ環境に MLBソースコードをクローンすることです。

[.console-input]
[source,bash]
----
git clone https://github.com/openshift-roadshow/mlbparks.git
----

NOTE: このガイドではスクリーンショットのためにIntelliJを使用していますが、ツールチェーンに関係なく動作するはずです。JBoss
Developer StudioとJBoss Developer Toolsには、IDEからほぼシームレスに実行できる機能が組み込まれています。

[#setup_the_build_of_the_war_file]
=== WARファイルのビルド設定
マシンにMavenがすべてセットアップされている場合は、`mlbparks` ディレクトリに `cd` して `mvn package` を実行してください。

[#docker_for_maven]
[TIP]
====
マシンに Maven がインストールされていないが、docker を実行できる場合は、代わりにリポジトリ ディレクトリをマウントし、コンテナー内からビルド コマンドを実行できます。

. 上記の `git clone` を実行したディレクトリ内から、次のコマンドを実行します。
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
docker run -it --rm --user 0 --name maven_builder -v ~/.kube:/home/jboss/.kube -v $(pwd):/workspaces -w /workspaces registry.access.redhat.com/ubi8/openjdk-11 /bin/bash
----
+
. 次に、このコマンドを（コンテナ内で）実行して、コンテナに最新バージョンの `oc` をローカルにインストールします。
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mkdir -p $HOME/bin && curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | \
    tar -xvzf - -C $HOME/bin/ oc && chmod 755 $HOME/bin/oc && ln -s $HOME/bin/oc $HOME/bin/kubectl
----
+
. 最後に、次のコマンドを実行して出力を比較し、ビルダー コンテナー内から OpenShift クラスターにまだ接続されていることを確認します。
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc whoami --show-server
----
+
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
https://{ocp4_starter_apps_domain}:30713
----

完了すると、以下に示すコマンドを実行できるようになります。
====

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
cd mlbparks
mvn package
----

ROOT.war の出力場所に注意してください。後でそのディレクトリが必要になります。

[#code_change]
=== コードの変更

ソースコードの変更です！

次のパスから `BackendController` Java クラスを編集します。

[.console-output]
[source,bash]
----
src/main/java/com/openshift/evg/roadshow/rest/BackendController.java
----

これは、サービスに関する基本情報を提供する REST エンドポイントであり、次の URL からアクセスできます。

[source,bash,role="copypaste",subs="+attributes"]
----
http://mlbparks-{ocp4_starter_project}.{ocp4_starter_apps_domain}/ws/info/
----

23 行目を変更して、"MLB Parks" の前に _AMAZING_ を追加してください。次のようになります。

[source,java]
----
return new Backend("mlbparks", "AMAZING MLB Parks", new Coordinates("39.82", "-98.57"), 5);
----

ファイルを保存し、ソース フォルダーのルートから `mvn package` を再度実行することを忘れないでください。

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
mvn package
----

[#doing_the_binary_build]
=== バイナリビルドの実行

WAR ファイルがビルドされたので、ビルドを開始しましょう。

Maven を使って WAR ファイルをビルドした場合:

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
oc start-build bc/mlbparks --from-file=target/ROOT.war --follow
----

NOTE: ターミナルでビルド出力を追跡する場合、--follow はオプションです。

ラベルと再作成デプロイメント戦略を使用すると、新しいデプロイメントが完了するとすぐにマップ名が更新されます。再作成デプロイメント戦略では、新しいデプロイメントを行う前にまずPodを破棄します。
Podが破棄されると、parksmap サービスは MLBParks マップをレイヤーから削除します。Podが復旧すると、レイヤーは新しいタイトルで自動的に追加されます。ローリングデプロイメントでは、このようなことは起こりません。
ローリングでは、古いPodを削除する前に新しいバージョンのPodを起動するためです。ローリング戦略により、ダウンタイムゼロのデプロイメントが可能になります。

Topology Viewからデプロイメントの進行状況を追跡でき、完了すると、新しいコンテンツが次の場所に表示されます。 

[source,bash,role="copypaste",subs="+attributes"]
----
http://mlbparks-{ocp4_starter_project}.{ocp4_starter_apps_domain}/ws/info/
----

これで、ビルドとデプロイのプロセスをスピードアップする方法がわかりました。
